name = "LosslessCompression"
uuid = "eacc5556-eb77-4bae-86dc-c85520419aca"
authors = ["Parth Deshmukh"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
